const ENDPOINT_FORM_RESPONSES_SLUG = 'form-responses';
const FIND_MY_UNCOMPLETED_FORM_RESPONSES_SLUG = 'find-my-uncompleted';
const FIND_OR_CREATE_MY_FORM_RESPONSE_SLUG = 'find-or-create';

export { ENDPOINT_FORM_RESPONSES_SLUG, FIND_MY_UNCOMPLETED_FORM_RESPONSES_SLUG, FIND_OR_CREATE_MY_FORM_RESPONSE_SLUG };
