const ROUTE_HOME_NAME = 'HOME';
const ROUTE_HOME_PATH = '/';

const ROUTE_CATEGORY_LIST_NAME = 'LIST';
const ROUTE_CATEGORY_LIST_PATH = '/category/:categoryId';

const ROUTE_CATEGORY_FORM_NAME = 'CATEGORY_FORM';
const ROUTE_CATEGORY_FORM_PATH = '/:formType/:formId';

export {
  ROUTE_HOME_NAME,
  ROUTE_HOME_PATH,
  ROUTE_CATEGORY_LIST_NAME,
  ROUTE_CATEGORY_LIST_PATH,
  ROUTE_CATEGORY_FORM_NAME,
  ROUTE_CATEGORY_FORM_PATH,
};
